<a href="https://colab.research.google.com/github/jvallalta/primeros-pasos/blob/main/Pytorch_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Primeros pasos con PyTorch

PyTorch es un framework para deep learning muy popular desarrollado por Facebook. Junto con TensorFlow conforman los dos frameworks de referencia para deep learning en la actualidad.



## Definiendo un modelo en PyTorch

In [ ]:
import torch
from torch import nn

In [ ]:
# Definimos el modelo como una clase
class RegresionLogistica(nn.Module):
    def __init__(self, input):
      #Método de inicialización con parámetros
      super().__init__()
      #Definimos la arquitectura
      self.reg_log = nn.Sequential(
          nn.Linear(input, 1),
          nn.Sigmoid()
      )
  
    def forward(self,x):
      return self.reg_log(x)

## Entrenando el modelo en PyTorch

In [ ]:
# Instanciamos un modelo
modelo = RegresionLogistica(16)

In [ ]:
# Definimos función de coste
criterion = nn.BCELoss()

In [ ]:
# Optimizador
optimizador = torch.optim.SGD(modelo.parameters(), lr=0.01)

In [ ]:
# Pendiente de revisar
import numpy as np
X = torch.tensor(np.random.rand(1000,16))
y = torch.tensor(np.log(range(1,1001)))

In [ ]:
# Bucle de entrenamiento
n_epochs = 100
for t in range(n_epochs):
  #Forward
  y_pred = modelo(X.float())
  loss = criterion(y_pred, y)
  #Paso optimización
  optimizador.zero_grad()
  loss.backward()
  optimizador.step()

## Tensores

Los tensores son una estructura de datos especializada que es muy similar a las matrices. En PyTorch, usamos tensores para codificar las entradas y salidas de un modelo, así como los parámetros del modelo.

Los tensores son similares a los ndarrays de NumPy, excepto que los tensores pueden ejecutarse en GPU u otros aceleradores de hardware. De hecho, los tensores y las matrices NumPy a menudo pueden compartir la misma memoria subyacente, lo que elimina la necesidad de copiar datos (consulte Puente con NumPy). Los tensores también están optimizados para la diferenciación automática (veremos más sobre eso más adelante en la sección Autograduación). Si está familiarizado con los ndarrays, se sentirá como en casa con la API de Tensor. Si no, ¡síguelo!

## Inicializando un tensor

In [41]:
import torch
import numpy as np

In [44]:
# Directamente de los datos
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

# De un array numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array) 

# A partir de otro tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) 
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2281, 0.0339],
        [0.3529, 0.8773]]) 



In [45]:
# Con valores aleatorios o constantes
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2366, 0.9153, 0.6165],
        [0.5332, 0.2502, 0.2716]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Atributos del tensor
Los atributos del tensor describen su tamaño, el tipo de datos y el dispositivo donde está almacenado

In [46]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operaciones con tensores

Más de 100 operaciones de tensor, que incluyen aritmética, álgebra lineal, manipulación de matrices (transposición, indexación, corte), muestreo y más, se describen detalladamente [aquí](https://pytorch.org/docs/stable/torch.html).

Cada una de estas operaciones se puede ejecutar en la GPU (normalmente a velocidades más altas que en una CPU). Si usa Colab, asigne una GPU yendo a Tiempo de ejecución> Cambiar tipo de tiempo de ejecución> GPU.

De forma predeterminada, los tensores se crean en la CPU. Necesitamos mover explícitamente los tensores a la GPU usando el método .to (después de verificar la disponibilidad de la GPU). Tenga en cuenta que copiar grandes tensores entre dispositivos puede resultar caro en términos de tiempo y memoria.

In [47]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [48]:
tensor.device

device(type='cpu')